export const DEFAULT_GOLD = 100
export const DEFAULT_WOOD = 100
export const DEFAULT_STONE = 100
export const DEFAULT_STORAGE_CAPACITY = 600

export const START_POPULATION = 100

export const EASY_ATTACK_COUNTDOWN_IN_MILISECONDS = 10 * 60 * 1000
export const MEDIUM_ATTACK_COUNTDOWN_IN_MILISECONDS = 0.5 * 60 * 1000 // TODO: change to 8 after testing
export const HARD_ATTACK_COUNTDOWN_IN_MILISECONDS = 5 * 60 * 1000

export const GAME_LOOP_DELAY_IN_MILISECONDS = 100
