export default {
  startScreenTemplateID: 'start-screen-template',
  startScreenHiddenClass: 'start__screen--hidden',
  startScreenOpenedClass: 'start__screen--opened',
  startScreenClosedClass: 'start__screen--closed',
  settingBtnID: 'settings-button',
  infoBtnID: 'info-button',
  startGameBtnID: 'start-game-button',
  characterDropdownID: 'character-dropdown',
  startScreenClass: 'start__screen',
  startScreenBgClass: 'start__screen--background',
  startScreenLogoClass: 'start__screen__logo',
  startScreenBtnOption: 'start__screen__button--option',
  startScreenLogoBgClass: 'start__screen__logo--background',
  startScreenBtnOptionSelected: 'start__screen__button--option--selected',
  backgroundAnimation: 'background__animation',
  logoAnimationOneClass: 'logo__animation--one',
  logoAnimationTwoClass: 'logo__animation--two',
}
